import React from "react";
import { Heading, PolicySection, TextM, PolicyText, PolicyHeading } from "../styles/appContainer"; // Assuming these are styled-components or similar

export function PrivacyPolicy() {
    // Make sure to update this date whenever the policy changes
    const lastUpdatedDate = "2025-03-27"; // UPDATE AS NEEDED
    const contactEmail = "johnlemonnft@dogepoundnft.com"; // Verify this email
    const selfHostedApiEndpoint = "https://mintpad-ape-terminal.onrender.com/api/generate-doge"; // Your self-hosted endpoint

    return (
        <PolicySection>
            <PolicyHeading>
                <Heading className="policy">GmAwoo Chrome Extension Privacy Policy</Heading>
                <p>Last updated: {lastUpdatedDate}</p>
            </PolicyHeading>

            {/* ... (Introduction, Definitions, Info Collection sections remain the same) ... */}
            <PolicyText>
                <Heading className="policy border">Introduction</Heading>
                <TextM className="policy">
                    Welcome to the GmAwoo Chrome Extension (“Extension”, “us”, “we”, or “our”).
                    <br />
                    This Privacy Policy governs your use of the GmAwoo Chrome Extension, which enhances the user experience on X.com (formerly Twitter.com) by adding interactive buttons and features. It explains how we collect, safeguard, and disclose information resulting from your use of our Extension.
                    <br /><br />
                    By installing and using this Extension, you agree to the collection and use of information in accordance with this policy.
                </TextM>
            </PolicyText>

            <PolicyText>
                <Heading className="policy border">Definitions</Heading>
                <TextM className="policy">
                    <strong>EXTENSION:</strong> means the GmAwoo Chrome browser extension.
                    <br />
                    <strong>SERVICE:</strong> means the features and functionality provided by the Extension.
                    <br />
                    <strong>PERSONAL DATA:</strong> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession). While the Extension primarily handles non-personal configuration data, certain data read from X.com or provided by the user could potentially contain Personal Data.
                    <br />
                    <strong>EXTENSION CONFIGURATION DATA:</strong> means data provided by the user or set via the Extension's popup interface to customize its behavior (e.g., Doge Numbers, username preference).
                    <br />
                    <strong>USAGE DATA:</strong> is data collected automatically, either generated by the use of the Service or from interactions with third-party services initiated by the Extension (e.g., logs from image servers or API calls containing IP addresses).
                    <br />
                    <strong>DATA CONTROLLER:</strong> means a natural or legal person who determines the purposes and means of processing personal data. For the purpose of this Privacy Policy, we are the Data Controller for the Extension Configuration Data we manage.
                    <br />
                    <strong>DATA PROCESSORS (OR SERVICE PROVIDERS):</strong> means any natural or legal person who processes data on behalf of the Data Controller. We use third-party Service Providers (like CDN and potentially AI APIs like Google Gemini) as detailed below.
                    <br />
                    <strong>DATA SUBJECT:</strong> is any living individual who is the subject of Personal Data.
                    <br />
                    <strong>USER:</strong> is the individual using our Extension. The User corresponds to the Data Subject.
                    <br />
                    <strong>X.COM:</strong> refers to the website formerly known as Twitter.com, where the Extension operates.
                </TextM>
            </PolicyText>

            <PolicyText>
                <Heading className="policy border">Information Collection and Use</Heading>
                <TextM className="policy">
                    We collect and use information primarily to provide and improve the functionality of the Extension on X.com.
                </TextM>
            </PolicyText>

            {/* MODIFIED SECTION BELOW */}
            <PolicyText>
                <Heading className="policy border">Types of Data Collected and Processed</Heading>
                <TextM className="policy">
                    <strong>1. Extension Configuration Data:</strong>
                    {/* ... (This part remains the same) ... */}
                    <br />
                        <strong>Doge Numbers:</strong> When you enter a "Doge Number" in the Extension popup, it is stored locally on your device using <code>chrome.storage.local</code>. This number is used to construct URLs for fetching specific Doge images.
                    <br />
                        <strong>Username Setting (`usernameset`):</strong> A flag indicating your preference for including usernames in GM/GN replies is stored locally using <code>chrome.storage.local</code>.
                    <br />
                        <strong>Purpose:</strong> This data is used solely to configure the Extension's image fetching and reply formatting features according to your preferences. It is stored locally and is not transmitted to our servers.
                    <br /><br />

                    <strong>2. Data Read from X.com:</strong>
                    {/* ... (This part remains the same) ... */}
                    <br />
                        <strong>Tweet Content and Metadata:</strong> To function, the Extension needs to read the content of the X.com pages you visit. This includes tweet text, usernames/display names associated with tweets, and the structure of the page (to find where to place buttons).
                    <br />
                        <strong>Purpose:</strong> This data is read dynamically to:
                    <br />
                            - Identify tweets and reply/like/retweet buttons for adding GM/GN buttons.
                    <br />
                            - Extract usernames for inclusion in replies (if the `usernameset` flag is enabled).
                    <br />
                            - Extract tweet text to provide context for the "ReplyGenAI🐶" feature.
                    <br />
                        <strong>Handling:</strong> This data is processed transiently. The Extension does *not* store this X.com page data, *except* when specific pieces (like tweet text) are explicitly sent to a service by user action (see below).
                    <br /><br />

                    <strong>3. Data Sent to Services:</strong> {/* Changed from Third-Party Services */}
                    <br />
                        <strong>Image Fetching (CloudFront):</strong> When you use the GM, GN, or Meme features, the Extension constructs an image URL using your locally stored `DogeNumber` and the required image type (e.g., `gm/`, `signadoptadoge/`). This URL points to <code>https://d3cvnrw4bpahxk.cloudfront.net/</code> (an Amazon Web Services Content Delivery Network). A request is sent to this URL to fetch the image.
                    <br />
                            <strong>Data Sent:</strong> The constructed URL path (containing the Doge Number and image type identifier).
                    <br />
                            <strong>Service Provider:</strong> AWS CloudFront. AWS logs standard web request data (e.g., your IP address, requested URL path, time of request) according to their own privacy policies. We do not receive this log data directly.
                    <br />
                            <strong>Purpose:</strong> To retrieve and display the relevant Doge images within the X.com interface.
                    <br /><br /> {/* Added line break */}

                    {/* === MODIFIED AI SECTION STARTS HERE === */}
                        <strong>AI Reply/Image Generation (ReplyGenAI🐶 Feature):</strong> When you click the "ReplyGenAI🐶" button and provide input:
                    <br />
                            <strong>Data Sent to Our Server:</strong>
                    <br />
                                - Your current `DogeNumber` (from local storage).
                    <br />
                                - The text content of the tweet you are replying to (read from the X.com page, URLs removed).
                    <br />
                                - The text prompt you enter into the pop-up dialog (`window.prompt`).
                    <br />
                            <strong>Destination (Our Server):</strong> This data is sent via an HTTPS POST request to our self-hosted API endpoint: <code>{selfHostedApiEndpoint}</code>.
                    <br />
                            <strong>Processing on Our Server:</strong> Our server receives this data solely to process your request. It acts as an intermediary, using the received information (primarily the prompt and potentially context from the tweet text) to make a request to Google's Gemini API to generate the requested image or text.
                    <br />
                            <strong>Data Storage Commitment:</strong> <strong>We do not store your Doge Number, the tweet text, or your specific prompt on our server beyond the immediate, transient processing required to interact with the Gemini API and return the result to you.</strong> Standard server logs (like IP address, request time, status code) may be generated but are not correlated with the content of your prompt or the tweet.
                    <br />
                            <strong>Interaction with Google Gemini:</strong> Our server sends a request (derived from your prompt) to Google's Gemini API. Google's handling of that data is governed by Google's own API Terms of Service and Privacy Policy. We recommend you review Google's policies if you have concerns about how they process data sent to their AI models.
                    <br />
                            <strong>Purpose:</strong> To generate a relevant text reply or a modified Doge image based on the tweet context and your prompt, utilizing our server as a proxy to Google's Gemini AI model.
                    <br />
                            <strong><span style={{ color: 'orange' }}>USER ACKNOWLEDGEMENT:</span></strong> By using the "ReplyGenAI🐶" feature, you acknowledge and consent to your prompt and related data being sent first to our self-hosted server (<code>{selfHostedApiEndpoint}</code>) for transient processing, and subsequently potentially being processed by Google's Gemini API according to their terms. While we commit not to store your prompt content, the data necessarily transits our server and is processed externally by Google Gemini.
                     {/* === MODIFIED AI SECTION ENDS HERE === */}
                    <br /><br />

                    <strong>4. Usage Data:</strong>
                    {/* ... (This part remains the same) ... */}
                    <br />
                        The Extension itself does not directly collect traditional Usage Data like your browsing history. However, when the Extension makes requests to Service Providers (CloudFront, our self-hosted API) on your behalf, those services may automatically collect standard technical data associated with the requests, such as your IP address, browser type/version, request timestamp, and requested resource. Collection by CloudFront is governed by AWS policies. Collection by our self-hosted API is limited to standard server logging as described above.
                    <br /><br />

                    <strong>5. Cookies:</strong>
                    {/* ... (This part remains the same) ... */}
                    <br />
                        The Extension does <strong>not</strong> use browser cookies. It uses the <code>chrome.storage.local</code> API provided by the browser to store your configuration settings (Doge Numbers, username flag) directly on your device.
                </TextM>
            </PolicyText>

            {/* ... (Use of Data, Retention of Data sections remain the same) ... */}
            <PolicyText>
                <Heading className="policy border">Use of Data</Heading>
                <TextM className="policy">
                    GmAwoo Extension uses the collected/processed data for the following purposes:
                    <br />
                    0.1. to provide and maintain the Extension's features on X.com;
                    <br />
                    0.2. to allow you to configure the Extension's behavior (Doge number, username preference);
                    <br />
                    0.3. to fetch and display appropriate Doge images from a CDN based on your configuration and actions;
                    <br />
                    0.4. to facilitate the generation of AI-powered replies or images via our self-hosted server (which uses Google Gemini) when you choose to use the ReplyGenAI feature; {/* Updated purpose */}
                    <br />
                    0.5. to automatically paste generated content (text or images) into the X.com reply interface upon your interaction;
                    <br />
                    0.6. to monitor and address technical issues with the Extension's functionality.
                </TextM>
            </PolicyText>

            <PolicyText>
                <Heading className="policy border">Retention of Data</Heading>
                <TextM className="policy">
                    <strong>Extension Configuration Data (`DogeNumbers`, `usernameset`):</strong> This data stored via <code>chrome.storage.local</code> persists on your device until you manually clear the Extension's storage, use the "Reset Doge" button, or uninstall the Extension.
                    <br /><br />
                    <strong>Data Processed by Our Server:</strong> As stated above, we do not retain the content of your prompts or related tweet text sent via the ReplyGenAI feature after the request to Google Gemini is completed and the response is returned. Standard, non-content server logs may be retained for typical operational periods (e.g., monitoring, security).
                    <br /><br/>
                    <strong>Data Sent to Third Parties (CloudFront, Google Gemini):</strong> We do not control the retention policies of AWS CloudFront or Google (for Gemini API interactions). Their retention of request logs or processed data is governed by their respective policies.
                </TextM>
            </PolicyText>

            {/* MODIFIED SECTION BELOW */}
            <PolicyText>
                <Heading className="policy border">Transfer of Data</Heading>
                <TextM className="policy">
                    Your information may be transferred to — and maintained on — computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ.
                    <br />
                    <strong>CloudFront:</strong> Image requests are handled by AWS CloudFront's global network.
                    <br />
                    {/* === MODIFIED TRANSFER SECTION STARTS HERE === */}
                    <strong>Our Self-Hosted API & Google Gemini:</strong> Data sent via the "ReplyGenAI🐶" feature is transferred first to our self-hosted server (hosted via Render.com at <code>{selfHostedApiEndpoint}</code>), the physical location of which may be outside your jurisdiction. Our server then makes a request involving your processed prompt to Google's Gemini API servers. The location of Google's servers processing these AI requests is determined by Google and may also be outside your jurisdiction.
                    {/* === MODIFIED TRANSFER SECTION ENDS HERE === */}
                    <br /><br />
                    Your consent to this Privacy Policy followed by your use of the Extension (and specifically the features involving these transfers) represents your agreement to these transfers. GmAwoo will take reasonable steps to ensure data sent *by the extension* uses secure protocols (HTTPS), and our self-hosted server also uses HTTPS. However, we cannot guarantee the internal security practices of external services like AWS or Google Gemini.
                </TextM>
            </PolicyText>

            {/* MODIFIED SECTION BELOW */}
            <PolicyText>
                <Heading className="policy border">Disclosure of Data</Heading>
                <TextM className="policy">
                    We may disclose information under the following circumstances:
                    <br />
                    <strong>To Service Providers / For Functionality:</strong> We transfer necessary data to enable the Extension's features:
                    <br />
                     {/* === MODIFIED DISCLOSURE SECTION STARTS HERE === */}
                        - AWS CloudFront (<code>d3cvnrw4bpahxk.cloudfront.net</code>): Receives requests containing URL paths derived from your Doge Number to serve images.
                    <br />
                        - Our Self-Hosted Server (<code>{selfHostedApiEndpoint}</code>): Receives Doge Number, tweet text, and user prompts when you use the ReplyGenAI feature, for transient processing and forwarding to Google Gemini.
                    <br />
                        - Google Gemini API: Receives processed prompts (originating from user input) via our server to generate AI content. Governed by Google's policies.
                     {/* === MODIFIED DISCLOSURE SECTION ENDS HERE === */}
                    <br />
                    <strong>Disclosure for Law Enforcement:</strong> Under certain circumstances, we may be required to disclose information (likely limited to server logs if compelled) if required to do so by law or in response to valid requests by public authorities.
                    <br />
                    <strong>Business Transaction:</strong> If we are involved in a merger, acquisition or asset sale, operational assets including the self-hosted server infrastructure might be transferred, but stored user prompt data would not be part of this as we don't retain it.
                    <br />
                    <strong>Protection of Rights:</strong> If we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Extension developers, our users, or others (e.g., investigating abuse based on server logs).
                    <br />
                    <strong>With Your Consent:</strong> For any other purpose disclosed by us when you provide the information, or with your explicit consent.
                </TextM>
            </PolicyText>

            {/* ... (Security of Data, Your Rights sections remain largely the same, maybe add Google Gemini to Service Providers list) ... */}
             <PolicyText>
                <Heading className="policy border">Security of Data</Heading>
                <TextM className="policy">
                    The security of your data is important to us. Extension Configuration Data is stored locally using Chrome's storage mechanisms. We use HTTPS for requests made by the Extension to external APIs (CloudFront, our self-hosted API). Our self-hosted server also uses HTTPS when communicating with Google Gemini where possible. However, remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect data interactions initiated by the Extension and processed by our server, we cannot guarantee absolute security, especially concerning data handled by external third-party services like AWS or Google.
                </TextM>
            </PolicyText>

            <PolicyText>
                <Heading className="policy border">Your Data Protection Rights (GDPR, CCPA, CalOPPA)</Heading>
                <TextM className="policy">
                    Depending on your location, you may have certain data protection rights.
                    <br />
                    <strong>Access, Update, Delete:</strong> For data stored locally (`DogeNumbers`, `usernameset`), you can manage this directly through the Extension's interface (input field, reset button) or by clearing the Extension's data in your browser settings / uninstalling. As we do not store the content of your prompts on our server, there is no prompt data held by us to access or delete. For data potentially held by third-party services (CloudFront logs, Google Gemini processing logs), you would need to contact those services directly, subject to their policies.
                    <br />
                    <strong>Rectification, Objection, Restriction, Portability:</strong> These rights primarily apply to Personal Data. As the Extension and our server minimize collection and storage of PII, exercising these rights mainly pertains to locally stored configuration or data held by third parties as mentioned above.
                    <br />
                    <strong>Withdraw Consent:</strong> You can withdraw consent for future data processing by ceasing to use the features that involve data transfer (especially ReplyGenAI) or by uninstalling the Extension.
                    <br />
                    <strong>Contact:</strong> If you wish to inquire about our data practices or server logs, please contact us at <strong>{contactEmail}</strong>. We may ask you to verify your identity.
                    <br />
                    <strong>Complaints:</strong> You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data.
                    <br />
                    <strong>CalOPPA:</strong> Users can use the Extension without providing identifying configuration data (though features might be limited). This policy is linked from the Extension's store listing. Policy changes will be indicated by updating the "Last updated" date and possibly noted in the store listing description.
                    <br />
                    <strong>"Do Not Track":</strong> The Extension does not track users across websites and does not alter its behavior based on Do Not Track signals.
                    <br />
                    <strong>CCPA "Do Not Sell":</strong> We do not sell your Personal Information for monetary value. The transfer of data to our self-hosted server and subsequently to Google Gemini for the AI feature is necessary for its function and is performed only upon your explicit action (clicking the button and submitting the prompt), constituting consent for that specific processing flow. If you wish to prevent such transfers, do not use the ReplyGenAI feature.
                </TextM>
            </PolicyText>

             {/* MODIFIED SECTION BELOW */}
            <PolicyText>
                <Heading className="policy border">Service Providers</Heading>
                <TextM className="policy">
                    We use third-party Service Providers and our own infrastructure to facilitate our Service:
                    <br />
                    - <strong>Amazon Web Services (AWS):</strong> Provides the CloudFront CDN (<code>d3cvnrw4bpahxk.cloudfront.net</code>) for hosting and delivering Doge images.
                    <br />
                    - <strong>Render.com:</strong> Hosts our self-hosted API server (<code>{selfHostedApiEndpoint}</code>).
                    <br />
                     {/* Added Google Gemini */}
                    - <strong>Google:</strong> Provides the Gemini API, which is used by our self-hosted server to generate AI content based on your prompts. Data handling is subject to Google's policies.
                </TextM>
            </PolicyText>

            {/* ... (Children's Privacy, Changes, Contact Us sections remain the same) ... */}
            <PolicyText>
                <Heading className="policy border">Children’s Privacy</Heading>
                <TextM className="policy">
                    Our Extension is not intended for use by children under the age of 18 (“Child” or “Children”). We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data without parental consent, please contact us.
                </TextM>
            </PolicyText>

            <PolicyText>
                <Heading className="policy border">Changes to This Privacy Policy</Heading>
                <TextM className="policy">
                    We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on the Extension's store listing page and updating the “Last updated” date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes are effective when they are posted.
                </TextM>
            </PolicyText>

            <PolicyText>
                <Heading className="policy border">Contact Us</Heading>
                <TextM className="policy">
                    If you have any questions about this Privacy Policy, please contact us by email: <strong>{contactEmail}</strong>.
                </TextM>
            </PolicyText>

        </PolicySection>
    );
}
